version: "3.3"
services:

  postgis:
    image: mdillon/postgis
    restart: always
    volumes:
      - ./postgis:/var/lib/postgresql/data
    container_name: postgis

  geospatial:
    build: ./geospatial
    image: finzone/geospatial
    restart: always
    ports:
      - 8787
    environment:
      - USER="${USER}"
      - PASSWORD="${PASSWORD}"
      - ROOT=true
    links:
      - postgis
    volumes:
      - "./${USER}:/home/${USER}"
    container_name: geospatial

  shinyproxy:
    build: ./shinyproxy
    image: finzone/shinyproxy
    restart: always
    container_name: shinyproxy
    ports:
      - 8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
