proxy:
  port: 8080
  authentication: simple
  users:
  - name: user
    password: password
  docker:
    internal-networking: true
  specs:
  - id: 01_finzone
    display-name: finzone
    description: Finzone
    container-cmd: ["R", "-e", "finzone::run()"]
    container-image: finzone/geospatial
    container-network: finzone_default

logging:
  file:
    shinyproxy.log
